<?php

/**
 * Admin "/learn" command
 *
 * Learns phrases from CSV-file generated by chatter_json_to_csv.php
 */

namespace Longman\TelegramBot\Commands\AdminCommands;

use Longman\TelegramBot\Commands\AdminCommand;
use Longman\TelegramBot\DB;
use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;
use PDO;

class LearnCommand extends AdminCommand
{
    /**
     * @var string
     */
    protected $name = 'learn';

    /**
     * @var string
     */
    protected $description = 'Learn';

    /**
     * @var string
     */
    protected $usage = '/learn <textfile>';

    /**
     * @var string
     */
    protected $version = '1.0.0';

    /**
     * Main command execution
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function execute(): ServerResponse
    {
        $message = $this->getMessage();
        $text = $message->getText(true);

        if (!is_numeric($text)) {
            $filePath = $this->telegram->getUploadPath() . DIRECTORY_SEPARATOR . trim($text);
            if (!file_exists($filePath)) {
                echo "File not found!\n";

                return Request::emptyResponse();
            }

            if ($file = fopen($filePath, "r")) {
                while (!feof($file)) {
                    $lines = fgetcsv($file, 10000);

                    $this->telegram->runCommands(['/teach ' . trim($lines[0]) . (isset($lines[1]) ? '<===<===<===' . trim($lines[1]) : '')]);
                    echo implode(' <===<===<=== ', $lines) . "\n";
                }
                fclose($file);
            }
        } else {
            $pdo = DB::getPdo();
            $sql = "
                    SELECT `text`
                    FROM `message`
                    WHERE `chat_id` = :chat_id AND `text` IS NOT NULL
                ";
            $sth = $pdo->prepare($sql);
            $sth->execute([':chat_id' => trim($text)]);
            $result = array_column($sth->fetchAll(PDO::FETCH_ASSOC), 'text');

            foreach ($result as $line) {
                $this->telegram->runCommands(['/teach ' . trim($line)]);
                echo $line . "\n";
            }
        }

        return Request::emptyResponse();
    }
}
